# NUMPY.array

In [4]:
import numpy as np

In [5]:
np.__version__

'1.17.0'

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [11]:
#纬度
x.ndim

1

In [12]:
X.ndim

2

In [13]:
x.shape

(10,)

In [14]:
X.shape

(3, 5)

In [15]:
x.size

10

In [16]:
X.size

15

### numpy.array数据访问

In [17]:
#索引
x[0]

0

In [18]:
x[-1]

9

In [19]:
X[0][0]

0

In [20]:
X[(0,0)]

0

In [21]:
#切片访问
x[0:5]

array([0, 1, 2, 3, 4])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [26]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [27]:
#引用的方式创建子矩阵
subX = X[:2,:3]
subX[0][0]=100
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [28]:
#克隆的方式创建子矩阵
subX = X[:2,:3].copy()
subX[0][0]=200
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### Reshape

In [29]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 合并操作

In [36]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [35]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [37]:
A = np.array([[1,2,3],[4,5,6]])
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([A,A],axis=-1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
z = np.array([666,666,666])
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [42]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [44]:
B = np.full((2,2),100)
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [46]:
x = np.arange(10)

In [48]:
x1,x2,x3 = np.split(x,[3,7])

In [49]:
x1

array([0, 1, 2])

In [50]:
x2

array([3, 4, 5, 6])

In [51]:
x3

array([7, 8, 9])

In [65]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
A1,A2 = np.split(A,[1])

In [67]:
A1

array([[0, 1, 2, 3]])

In [68]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
A1,A2 = np.split(A,[1],axis=1)

In [70]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [71]:
A2

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [72]:
X,y = np.hsplit(A,[-1])
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [73]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [74]:
y[:,0]

array([ 3,  7, 11, 15])

### numpy.array中的运算

In [2]:
#每个元素*2
#pythonList
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
   A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
#每个元素*2
#numpy.array
import numpy as np
L = np.array([i for i in range(10)])
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
A = 2*L
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Funcitons

In [7]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [9]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [11]:
#浮点数除法
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [12]:
#整数除法
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [13]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [14]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [15]:
#绝对值
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [17]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [18]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [19]:
#对每个元素取e的X次方
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [21]:
#对每个元素取3的X次方
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [22]:
#对每个元素取3的X次方
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [23]:
#以e为底
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [24]:
#以2为底
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

### 矩阵运算

In [26]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [27]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [28]:
A + B

array([[10, 11],
       [12, 13]])

In [29]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [30]:
#对应元素相乘
A * B

array([[ 0, 10],
       [20, 30]])

In [31]:
#对应元素相除
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [32]:
#矩阵相乘
A.dot(B)

array([[10, 10],
       [50, 50]])

In [33]:
#矩阵转置
A.T

array([[0, 2],
       [1, 3]])

### 向量与矩阵的运算

In [34]:
v = np.array([1,2])
v + A

array([[1, 3],
       [3, 5]])

In [35]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [36]:
np.vstack([v]*A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [37]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [38]:
np.tile(v,(2,1)) + A

array([[1, 3],
       [3, 5]])

In [39]:
v * A

array([[0, 2],
       [2, 6]])

In [40]:
v.dot(A)

array([4, 7])

In [41]:
#numpy自动判断是否转为列向量相乘
A.dot(v)

array([2, 8])

### 矩阵的逆

In [44]:
#只有方阵可求逆
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [45]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [46]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [52]:
#伪逆矩阵
X = np.arange(16).reshape(2,8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [53]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [54]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

### 聚合操作

In [63]:
import numpy as np
L = np.random.random(100)
L

array([0.25494681, 0.16480831, 0.76040006, 0.66310372, 0.09365156,
       0.41929097, 0.89555593, 0.76261681, 0.29928658, 0.71060412,
       0.19081938, 0.04759739, 0.58121925, 0.10658595, 0.66844674,
       0.61488992, 0.62544439, 0.49366416, 0.25517653, 0.06607134,
       0.69948843, 0.30568104, 0.64193831, 0.58704769, 0.99333603,
       0.70430164, 0.43534206, 0.77539159, 0.68399916, 0.75604663,
       0.76328972, 0.48072416, 0.59042929, 0.51267657, 0.97508475,
       0.89982175, 0.62179534, 0.15004887, 0.11966337, 0.90716694,
       0.70645701, 0.20540749, 0.34122259, 0.91613573, 0.15337804,
       0.83068536, 0.49365316, 0.9406553 , 0.62171434, 0.1038072 ,
       0.07329828, 0.14316986, 0.21591696, 0.99223084, 0.86011056,
       0.61885867, 0.44941531, 0.74893635, 0.01642987, 0.36676776,
       0.60644072, 0.38045485, 0.08367956, 0.68719397, 0.08809805,
       0.24749781, 0.84226383, 0.61921671, 0.75856734, 0.6830731 ,
       0.93710359, 0.87124662, 0.92077048, 0.23612835, 0.91388

In [64]:
#求和操作
#python自带sum方法
%timeit sum(L)
#numpy提供效率更高的sum方法
%timeit np.sum(L)

19.7 µs ± 2.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.72 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
#numpy面向对象的sum方法
L.sum()

51.72151787719719

In [68]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
#numpy按行进行对每列求和
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [70]:
#numpy按列进行对每行求和
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [72]:
#numpy其他聚合操作
np.min(X)

0

In [73]:
np.max(X)

15

In [74]:
#所有元素的乘积
np.prod(X)

0

In [75]:
#所有元素的平均值
np.mean(X)

7.5

In [76]:
#所有元素的中位数
np.median(X)

7.5

In [80]:
v = np.arange(9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
#求百分位点的值
for percent in [0,25,50,75,100]:
    print(np.percentile(v,q=percent))

0.0
2.0
4.0
6.0
8.0


In [82]:
#所有元素的方差
np.var(v)

6.666666666666667

In [83]:
#所有元素的标准差
np.std(v)

2.581988897471611

In [84]:
#取一组均值为0标准差为1正态分布的随机数
x = np.random.normal(0,1,size=100)
x

array([ 0.05078059, -1.40516978,  0.0163852 ,  1.22462829,  0.22635619,
        2.13284831, -1.44980835, -0.85162377, -0.16450832,  1.16892736,
        1.59066889, -0.12746883, -0.04410627,  0.56964338, -1.56756997,
       -0.52786913,  1.08498869,  1.95212006,  0.46334594, -0.17141266,
       -1.06227873, -1.15461131, -0.45204117,  0.24231168,  0.92418958,
        1.22890634,  1.4068371 , -0.64313239, -1.76611477,  1.25716897,
       -0.42847476,  0.21789583, -0.70507094,  0.53349407, -0.33456028,
       -0.14235387,  0.21344374, -1.08005478, -1.29476957, -2.55106545,
       -0.17378734,  1.33067404,  1.30878585, -2.26954047,  0.89336011,
        1.16008665, -2.80919159,  0.45449442,  1.09330043,  0.74158558,
        1.54535859,  0.61024839,  0.50326859, -0.08286718, -0.49608405,
        1.30334473, -0.22541353,  0.28725766,  0.66268085, -1.24907355,
        0.57067399,  1.40978519,  0.75268657,  1.26834038, -0.8730579 ,
       -0.05858077, -0.44244931,  0.9940141 , -0.38380381,  0.00

In [85]:
np.mean(x)

0.026956858044466236

In [86]:
np.std(x)

1.0692199860399354

### 索引

In [87]:
np.min(x)

-2.809191588096685

In [88]:
#查询最小值的索引
np.argmin(x)

46

In [89]:
x[46]

-2.809191588096685

### 在排序中使用索引

In [91]:
#对向量进行乱序处理
x = np.arange(16)
np.random.shuffle(x)
x

array([ 5, 14,  1,  8,  7, 12,  2, 10,  6,  4, 11, 13,  9, 15,  3,  0])

In [92]:
#对向量进行排序
#np.sort返回排好序的新对象
newX = np.sort(x)
newX

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
#面向对象的sort对对象本身排序
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [97]:
#对矩阵排序
X = np.random.randint(10,size=(4,4))
X

array([[3, 7, 3, 6],
       [1, 5, 2, 1],
       [0, 1, 0, 1],
       [7, 4, 7, 3]])

In [100]:
#默认按列对行进行排序
np.sort(X)

array([[3, 3, 6, 7],
       [1, 1, 2, 5],
       [0, 0, 1, 1],
       [3, 4, 7, 7]])

In [101]:
#按行对列进行排序
np.sort(X,axis=0)

array([[0, 1, 0, 1],
       [1, 4, 2, 1],
       [3, 5, 3, 3],
       [7, 7, 7, 6]])

In [103]:
np.random.shuffle(x)
x

array([15, 11, 10,  6,  2,  1, 12,  7,  0,  9,  5, 13,  8,  3, 14,  4])

In [104]:
#返回排序后的索引
np.argsort(x)

array([ 8,  5,  4, 13, 15, 10,  3,  7, 12,  9,  2,  1,  6, 11, 14,  0])

In [105]:
#快速排序中的切片处理
#向量中比3大的放在3的右侧，比3小的放在3的右侧
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  5,  6,  7, 11,  9, 12, 13,  8, 10, 14, 15])

In [106]:
#返回切片处理的索引
np.argpartition(x,3)

array([ 8,  5,  4, 13, 15, 10,  3,  7,  1,  9,  6, 11, 12,  2, 14,  0])

### Fancy Indexing

In [107]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [109]:
#索引数组
inx = [3,5,8]
x[inx]

array([3, 5, 8])

In [110]:
#用索引矩阵得到矩阵
inx = np.array([[0,2],
               [1,3]])
x[inx]

array([[0, 2],
       [1, 3]])

In [111]:
#在矩阵中用坐标索引获取元素
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
xIndex = np.array([0,1,2])
yIndex = np.array([0,1,2])
X[xIndex,yIndex]

array([ 0,  5, 10])

In [113]:
X[0,yIndex]

array([0, 1, 2])

In [115]:
X[2:4,yIndex]

array([[ 8,  9, 10],
       [12, 13, 14]])

In [116]:
yIndex = [True,False,True,True]
X[:2,yIndex]

array([[0, 2, 3],
       [4, 6, 7]])

### numpy.array的比较

In [117]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [118]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [119]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [120]:
np.sum(x<3)

3

In [121]:
np.count_nonzero(x<3)

3

In [123]:
np.any(x == 16)

False

In [124]:
np.all(x >= 0)

True

In [125]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.sum(X%2 == 0,axis=1)

array([2, 2, 2, 2])

In [127]:
np.sum(X%2 == 0,axis=0)

array([4, 0, 4, 0])

In [128]:
np.sum((x > 3) & (x < 10))

6

In [130]:
np.sum((x % 2 == 0) | (x > 14))

9

In [133]:
np.sum(~(x==0))

15

In [134]:
x[x<5]

array([0, 1, 2, 3, 4])

In [135]:
x[x%2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [136]:
X[X[:,3]%3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])